spring.datasource.url=jdbc:postgresql://localhost:5432/reminer
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
telegram.bot.token=7957785508:AAHGx6dP4iGtaFqMM5ehRx7g6AUCDrLpfm8

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect